spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/Ecommerce?createDatabaseIfNotExist=true
    username: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
